# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 21:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla_curso', models.CharField(max_length=5, unique=True)),
                ('nome_curso', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(blank=True, max_length=240, null=True, unique=True)),
                ('carga_horaria', models.SmallIntegerField(blank=True, null=True)),
                ('teoria_disciplina', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('pratica_disciplina', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('ementa_disciplina', models.TextField(blank=True, null=True)),
                ('competencias_disciplina', models.TextField(blank=True, null=True)),
                ('habilidades_disciplina', models.TextField(blank=True, null=True)),
                ('conteudo_disciplina', models.TextField(blank=True, null=True)),
                ('bibliografia_basica_disciplina', models.TextField(blank=True, null=True)),
                ('bibliografia_complementar_disciplina', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gradecurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_grade', models.SmallIntegerField(blank=True, null=True)),
                ('semestre_grade', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'gradecurricular',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_periodo', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('ra_aluno', models.OneToOneField(db_column='ra', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('celular', models.CharField(max_length=11, null=True, verbose_name='Celular')),
                ('curso', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('ra_professor', models.OneToOneField(db_column='ra', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('celular', models.CharField(max_length=11, null=True, verbose_name='Celular')),
                ('apelido', models.CharField(max_length=30, verbose_name='Apelido')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usuario',),
        ),
    ]
