# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla_curso', models.CharField(max_length=5, unique=True)),
                ('nome_curso', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240)),
                ('carga_horaria', models.SmallIntegerField()),
                ('aula_teorica', models.DecimalField(decimal_places=3, max_digits=10)),
                ('aula_pratica', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ementa', models.TextField(blank=True, null=True)),
                ('competencias', models.TextField(blank=True, null=True)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('bibliografia_basica', models.TextField(blank=True, null=True)),
                ('bibliografia_complementar', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('parent_link', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('celular', models.CharField(max_length=11, verbose_name='Celular')),
                ('semestre', models.IntegerField(verbose_name='Semestre')),
                ('curso', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('parent_link', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('celular', models.CharField(max_length=11, null=True, verbose_name='Celular')),
                ('apelido', models.CharField(max_length=30, unique=True, verbose_name='Apelido')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usuario',),
        ),
    ]
