# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aluno_cursos_disciplina_gradecurricular_periodo_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoQuestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_questao', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'arquivo_questao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArquivoResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_resposta', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'arquivo_resposta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CursoTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'curso_turma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_disciplina_ofertada', models.SmallIntegerField(blank=True, null=True)),
                ('semestre_disciplina_ofertada', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'disciplina_ofertada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'matricula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodoDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_periodo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'periodo_disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_questao', models.IntegerField(blank=True, null=True)),
                ('data_limite_entrega', models.CharField(blank=True, max_length=10, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'questao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_aluno', models.IntegerField(blank=True, null=True)),
                ('data_avaliacao', models.CharField(blank=True, max_length=10, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('avaliacao', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_de_envio', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'resposta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_turma', models.CharField(blank=True, max_length=1, null=True, unique=True)),
                ('turno', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'turma',
                'managed': False,
            },
        ),
    ]
