# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aluno_codigomatricula_curso_cursoturma_disciplina_disciplinaofertada_matricula_professor_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoQuestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_questao', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'arquivo_questao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArquivoResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_resposta', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'arquivo_resposta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GradeCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_grade', models.SmallIntegerField()),
                ('quantidade_semestres', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'grade_curricular',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_periodo', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodoDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'periodo_disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_questao', models.IntegerField()),
                ('data_limite_entrega', models.CharField(max_length=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_questao', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'questao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_aluno', models.IntegerField()),
                ('data_avaliacao', models.CharField(max_length=10)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('avaliacao', models.TextField()),
                ('descricao', models.TextField()),
                ('data_de_envio', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'resposta',
                'managed': False,
            },
        ),
    ]
