# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 23:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_disciplina_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla_curso', models.CharField(max_length=5, unique=True)),
                ('nome_curso', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField()),
                ('semestre', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'disciplina_ofertada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_turma', models.CharField(max_length=2)),
                ('turno', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'turma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('parent_link', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('celular', models.CharField(max_length=11, verbose_name='Celular')),
                ('semestre', models.IntegerField(default=1, verbose_name='Semestre')),
                ('curso', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usuario',),
        ),
    ]
