# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aluno_curso_disciplina_gradecurricular_periodo_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_type',
            field=models.CharField(default='C', max_length=1, verbose_name='Tipo de usuário'),
        ),
    ]
