# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_arquivoquestao_arquivoresposta_gradecurricular_periodo_periododisciplina_questao_resposta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='curso',
            new_name='sigla_curso',
        ),
    ]
