# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171126_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ano_ingresso',
            field=models.IntegerField(default=2017, verbose_name='Ano'),
        ),
    ]
