# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171109_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='ra_professor',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
