# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_arquivoquestao_arquivoresposta_cursoturma_disciplinaofertada_matricula_periododisciplina_questao_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='semestre',
            field=models.IntegerField(verbose_name='semestre'),
        ),
    ]
