# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171123_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='sigla_curso',
            new_name='curso',
        ),
        migrations.AlterModelTable(
            name='turma',
            table='turma',
        ),
    ]
