# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aluno_ano_ingresso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ano_ingresso',
            field=models.IntegerField(verbose_name='Ano'),
        ),
    ]
