# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171125_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_questao', models.IntegerField()),
                ('data_limite_entrega', models.CharField(max_length=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_questao', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'questao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_aluno', models.IntegerField()),
                ('data_avaliacao', models.CharField(max_length=10)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('avaliacao', models.TextField()),
                ('descricao', models.TextField()),
                ('data_de_envio', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'resposta',
                'managed': False,
            },
        ),
    ]
