# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171112_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='semestre',
            field=models.IntegerField(verbose_name='Semestre'),
        ),
    ]
