# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 00:52
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_questao_resposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoQuestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_questao', models.IntegerField()),
                ('arquivo_questao', models.FileField(upload_to=core.models.monta_arquivo_questao)),
            ],
            options={
                'db_table': 'arquivo_questao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArquivoResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_resposta', models.FileField(upload_to=core.models.monta_arquivo_resposta)),
            ],
            options={
                'db_table': 'arquivo_resposta',
                'managed': False,
            },
        ),
    ]
