# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171109_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='ra_aluno',
            new_name='parent_link',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='ra_professor',
            new_name='parent_link',
        ),
    ]
