# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171109_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivoquestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_questao', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'arquivoquestao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arquivosresposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_resposta', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'arquivosresposta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cursoturma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cursoturma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplinaofertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_disciplina_ofertada', models.SmallIntegerField(blank=True, null=True)),
                ('semestre_disciplina_ofertada', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'disciplinaofertada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'matricula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periododisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_periodo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'periododisciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_questao', models.IntegerField(blank=True, null=True)),
                ('data_limite_entrega', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'questao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_aluno', models.IntegerField(blank=True, null=True)),
                ('data_avaliacao', models.DateField(blank=True, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('avaliacao', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_de_envio', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resposta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_turma', models.CharField(blank=True, max_length=1, null=True, unique=True)),
                ('turno', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'turma',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='professor',
            name='apelido',
            field=models.CharField(max_length=30, unique=True, verbose_name='Apelido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_type',
            field=models.CharField(max_length=1, verbose_name='Tipo de usuário'),
        ),
    ]
