# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=12)),
                ('remetente', models.CharField(max_length=12)),
                ('curso', models.CharField(max_length=100)),
                ('turma', models.CharField(max_length=100)),
                ('mensagem', models.CharField(max_length=500)),
                ('data_envio', models.DateTimeField()),
            ],
        ),
    ]
