# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=80)),
                ('celular', models.CharField(max_length=11)),
                ('sigla_curso', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'aluno',
                'managed': False,
            },
        ),
    ]
